### ISSUE TITLE
Some difference between the code and paper

### ISSUE THREAD

**Issue by Iceland-Leo** [ninatu/everything_at_once#1]
1、I found that there is a "Transformer Blocks" for all the embeddings(from all modalities) in the paper Figure 2. But in your code, one "Transformer Blocks" for each modal embeddings, one "Transformer Blocks" for cross modal embeddings later. 
2、Question: If I have 'n' modals, the number of cross modal embedding will be 2 ** n - n - 2? For example, if I have A/B/C/D modals, then the cross-modal is 'AB', 'AC', 'AD', 'BC', 'BD', 'CD', 'ABC', 'ABD', 'ACD', 'BCD' ?

**Comment by ninatu** [comment]
Hi! 
1. We have only one Fusion transformer and apply it for all modality combinations (line 31 in fusion_model.py). I'm not sure what you mean under "one Transformer Blocks for each modal embeddings", could you please point it out on the line of code, so I can help?
2. Yes, indeed, the number of cross-modal embeddings will exponentially grow with the number of modalities. In the paper, we suggested that in this case, some modality combinations may be randomly dropped during training to make it feasible, similarly to how that's done in Perceiver.

**Comment by Iceland-Leo** [comment]
For the question 1, https://github.com/ninatu/everything_at_once/blob/b4cd3a70076ea3ea2b40832aa3e2afab50495c47/everything_at_once/model/fusion_model.py#L158

**Comment by ninatu** [comment]
This is the same fusion transformer (self.fusion) and we apply it for all modality combinations: singles - text, video, audio - lines 158-160, and pairs -  text-video, text-audio, video-audio - lines 172-176

**Comment by Iceland-Leo** [comment]
I got it. &nbsp;Thank you!



发自我的iPhone


------------------ Original ------------------
From: Nina Shvetsova ***@***.***&gt;
Date: Mon,Jul 4,2022 9:43 PM
To: ninatu/everything_at_once ***@***.***&gt;
Cc: Liucheng ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [ninatu/everything_at_once] Some difference between the code andpaper (Issue #1)





 
This is the same fusion transformer (self.fusion) and we apply it for all modality combinations: singles - text, video, audio - lines 158-160, and pairs -  text-video, text-audio, video-audio - lines 172-176
