### ISSUE TITLE
Regarding feature computation for S3D and CLIP

### ISSUE THREAD

**Issue by bpiyush** [ninatu/everything_at_once#10]
Hi Nina! Great work!

Thanks for the code release. I was wondering if you have scripts for S3D and CLIP feature computations handy with you? If so, could you please share them? Thanks.

**Comment by ninatu** [comment]
Hi! 

Thanks so your interest in our work. For feature extraction, we basically use the released code for the [S3D model](https://github.com/antoine77340/S3D_HowTo100M) and [CLIP model](https://github.com/openai/CLIP). I will try to publish our scripts in the near future.

**Comment by bpiyush** [comment]
Thank you!
