### ISSUE TITLE
 What hardware resources do I need to run your model and data? 

### ISSUE THREAD

**Issue by GeoffreyWu8** [ninatu/everything_at_once#5]
Hi Shvedova,
Congratulations on your team's paper being accepted by CVPR. I have a slight question. What hardware resources do you need to run your model and data? Because I have three 2080Ti and it still doesn't work. The message is below:
>>RuntimeError: CUDA out of memory. Tried to allocate 96.00 MiB (GPU 0; 10.76 GiB total capacity; 9.81 GiB already allocated; >>88.31 MiB free; 9.82 GiB reserved in total by PyTorch)
The command that I used is : 'python test.py --n_gpu 3  --config configs/evaluation/msrvtt_at_once.yaml  --resume pretrained_models/everything_at_once_tva/latest_model.pth'
Looking forward to your reply.
Best wishes,
Feng.

**Comment by ninatu** [comment]
Hi!

We used one V100 32GB GPU for testing. But indeed model takes about ~ 13Gb gpu memory. And most of it is just loaded weights in checkpoint (model, optimizer, etc)
You can change the line  
```
checkpoint = torch.load(config.resume)
```
to 
```
checkpoint = torch.load(config.resume, map_location='cpu')
```
And gpu utilization becomes 5Gb.  I guess it should work for one 2080Ti.
