### ISSUE TITLE
Token concatenate question

### ISSUE THREAD

**Issue by nemo0526** [ninatu/everything_at_once#9]
Hello, may I ask where you concatenate the input token and separate the output token?

**Comment by ninatu** [comment]
Hi! 
Do you mean the concatenation of tokens of different modalities (before appling a fusion transformer)? 
[Here](https://github.com/ninatu/everything_at_once/blob/main/everything_at_once/model/fusion_model.py#L172 ) we are inputting them in a fusion block, and [where](https://github.com/ninatu/everything_at_once/blob/4daeab616274eef76487e9e132c2fd35d3838496/everything_at_once/model/utils/fusion_transformer.py#L50) they are concatenated, and then [here](https://github.com/ninatu/everything_at_once/blob/4daeab616274eef76487e9e132c2fd35d3838496/everything_at_once/model/utils/fusion_transformer.py#L75) and later they are separated again based on modality.

**Comment by nemo0526** [comment]
Ok, thanks for your reply. It helps a lot!

**Comment by nemo0526** [comment]
> Ok, thanks for your reply. I found that there is one more concatenation before Multi-modal Shared
Embedding Space in the paper, but it seems not in the fusion_model.py.
![cat](https://user-images.githubusercontent.com/63770299/208949247-435fe20f-2666-485a-ab0c-6b07c20ee7e2.png)

**Comment by ninatu** [comment]
Hi! This one happens [here](https://github.com/ninatu/everything_at_once/blob/4daeab616274eef76487e9e132c2fd35d3838496/everything_at_once/model/fusion_model.py#L185) after projection.

**Comment by nemo0526** [comment]
Ok, thank you very much!
